name: khubzy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  intl: ^0.20.2
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.63.0
  http: ^0.13.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_users.json
    - assets/mock_bakery_data.json
    - assets/images/Kubzy.png
