// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBggWcwCOIJMQP_XNSJKqIah5BeLhGnIwU',
    appId: '1:502772812131:web:d5caaca00cd61e0ba6ab56',
    messagingSenderId: '502772812131',
    projectId: 'khubzy-51aa8',
    authDomain: 'khubzy-51aa8.firebaseapp.com',
    storageBucket: 'khubzy-51aa8.firebasestorage.app',
    measurementId: 'G-KNV4FQQTG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmMGXptveamc6rFwy0XtbNSimzs4K_kI',
    appId: '1:502772812131:android:6fb2ec67a4326790a6ab56',
    messagingSenderId: '502772812131',
    projectId: 'khubzy-51aa8',
    storageBucket: 'khubzy-51aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNFyVLoQam0GLWkSMib6HMQnIRxxlxIY',
    appId: '1:502772812131:ios:532d95e99dda9337a6ab56',
    messagingSenderId: '502772812131',
    projectId: 'khubzy-51aa8',
    storageBucket: 'khubzy-51aa8.firebasestorage.app',
    iosBundleId: 'com.example.khubzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNFyVLoQam0GLWkSMib6HMQnIRxxlxIY',
    appId: '1:502772812131:ios:532d95e99dda9337a6ab56',
    messagingSenderId: '502772812131',
    projectId: 'khubzy-51aa8',
    storageBucket: 'khubzy-51aa8.firebasestorage.app',
    iosBundleId: 'com.example.khubzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBggWcwCOIJMQP_XNSJKqIah5BeLhGnIwU',
    appId: '1:502772812131:web:8f70945c50ba9ec3a6ab56',
    messagingSenderId: '502772812131',
    projectId: 'khubzy-51aa8',
    authDomain: 'khubzy-51aa8.firebaseapp.com',
    storageBucket: 'khubzy-51aa8.firebasestorage.app',
    measurementId: 'G-3NJ624Y0T0',
  );
}
